/*
create database customer_behavior
GO
*/


--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) revenue
FROM dbo.customer
GROUP BY gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount
FROM dbo.customer
WHERE discount_applied = 'yes'
AND purchase_amount > (SELECT AVG(purchase_amount) FROM dbo.customer)

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 item_purchased, ROUND(AVG(review_rating),2) average_product_rating
FROM dbo.customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, AVG(purchase_amount)
FROM dbo.customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status, COUNT(customer_id) total_customers,
ROUND(AVG(purchase_amount),2) avg_spend,
ROUND(SUM(purchase_amount),2) total_spend
FROM dbo.customer
GROUP BY subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 item_purchased,
FORMAT(SUM(CASE WHEN discount_applied = 'Yes' THEN 1.0 ELSE 0 END) / COUNT(*), 'P2') AS discount_rate
FROM dbo.customer
GROUP BY item_purchased
ORDER BY discount_rate DESC

-- WHEN A HAT WAS SOLD 50% OF THE TIME IT WAS SOLD IN DISCOUND

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH customer_type AS (
			SELECT customer_id, previous_purchases,
			CASE 
				WHEN previous_purchases = 1 THEN 'New'
				WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
				ELSE 'Loyal' END customer_segment
			FROM dbo.customer)
SELECT customer_segment, COUNT(*) 'Number_of_Customer'
FROM customer_type
GROUP BY customer_segment
ORDER BY Number_of_Customer DESC

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS(
				SELECT category, item_purchased, SUM(purchase_amount) total_sales,
				ROW_NUMBER() OVER (PARTITION BY category ORDER BY SUM(purchase_amount) DESC) item_rank
				FROM dbo.customer
				GROUP BY category, item_purchased)

SELECT item_rank, category, item_purchased, total_sales
FROM item_counts
WHERE item_rank <= 3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) repeat_buyers
FROM dbo.customer
WHERE previous_purchases > 5
GROUP BY subscription_status

--Q10. What is the revenue contribution of each age group? 
SELECT age_group, SUM(purchase_amount) total_revenue
FROM dbo.customer
GROUP BY age_group
ORDER BY total_revenue DESC

